name: Marked Fares Worker
on:
  push:
    branches: ["master"]

  schedule:
    - cron: '*/10 * * * *' # every 10 minutes

jobs:
  marked-fares-worker:
    name: marked-fares-worker
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: workers
    env:
      PUPPETEER_SKIP_DOWNLOAD: "true"
      VITE_SMTP_CONNECTION_STRING: ${{ secrets.VITE_SMTP_CONNECTION_STRING }}
      VITE_FIREBASE_CONFIG_JSON: ${{ secrets.VITE_FIREBASE_CONFIG_JSON }}
      VITE_FIREBASE_FUNCTIONS_URL: ${{ secrets.VITE_FIREBASE_FUNCTIONS_URL }}
      VITE_FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.VITE_FIREBASE_SERVICE_ACCOUNT_JSON }}
      VITE_SCRAPERS_URL: ${{ secrets.VITE_SCRAPERS_URL }}
      VITE_LOKI_LOGGING_URL: ${{ secrets.VITE_LOKI_LOGGING_URL }}
      VITE_LOKI_LOGGING_UID: marked_fares_worker
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run marked-fares-worker
