name: Scraper Tests
on:
  push:
  schedule:
    - cron: '55 */10 * * *'

jobs:
  run-scraper-tests:
    name: run-scraper-tests
    runs-on: ubuntu-latest
    environment: ci
    env:
      PUPPETEER_SKIP_DOWNLOAD: "true"
      VITE_LIVE_SCRAPER_TESTS: 1
      VITE_BROWSERLESS_AWS_PROXY_URL: ${{ secrets.VITE_BROWSERLESS_AWS_PROXY_URL }}
      VITE_BROWSERLESS_AWS_PROXY_API_KEY: ${{ secrets.VITE_BROWSERLESS_AWS_PROXY_API_KEY }}
      VITE_FIREBASE_CONFIG_JSON: ${{ secrets.VITE_FIREBASE_CONFIG_JSON }}
      VITE_LOKI_LOGGING_URL: ${{ secrets.VITE_LOKI_LOGGING_URL }}
      VITE_LOKI_LOGGING_UID: scraper_tests
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test-scrapers
      - uses: actions/upload-artifact@v3
        with:
          name: scraper-test-results
          path: test-results.json
          if-no-files-found: error
