name: Upload functions to Firebase Functions
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    name: upload-firebase-functions
    environment: workers
    timeout-minutes: 5
    env:
      PUPPETEER_SKIP_DOWNLOAD: "true"
      VITE_FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.VITE_FIREBASE_SERVICE_ACCOUNT_JSON }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm install --frozen-lockfile
        working-directory: ./functions
      - run: echo -E "$VITE_FIREBASE_SERVICE_ACCOUNT_JSON" > /tmp/creds.json
      - run: GOOGLE_APPLICATION_CREDENTIALS=/tmp/creds.json pnpm deploy-functions
